#!/bin/bash
set -e

echo "Stopping WordPanel service..."
systemctl stop wordpanel.service
systemctl disable wordpanel.service

# Remove the virtual environment to clean up space
rm -rf /opt/wordpanel/venv

exit 0
